/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2011-12-15 13:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.servlet.browse.Files;
import com.servlet.upload.FileUpload;
import com.pgrou.pdfcorrection.Main;

public final class correction_005fhtml_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/script/PDFCorrectionInterface.js", Long.valueOf(1323955374000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" /> <title>PDFCorrector</title>\n");
      out.write("       <script type='text/JavaScript'>");
      out.write("var clic;\n");
      out.write("var mistakeMarkup;\n");
      out.write("\n");
      out.write("function init() {\n");
      out.write("\n");
      out.write("alert(\"Vous devez corriger toutes les erreurs avant de valider !\");\n");
      out.write("\n");
      out.write("// Cache la fenÃªtre de suggestion au dÃ©marrage\n");
      out.write("\t$(\"#suggestions\").hide();\n");
      out.write("\t\n");
      out.write("\t// Affiche la liste de suggestions\n");
      out.write("\tshowSuggestions();\n");
      out.write("}\n");
      out.write("window.onload = init; \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function showSuggestions() {\t\n");
      out.write("\t$(\".orthoerror, .grammerror\").click(function(e) {\n");
      out.write("\t\t// RÃ©cupÃ¨re l'erreur qui a Ã©tÃ© clickÃ©e\n");
      out.write("\t\tmistakeMarkup = $(this);\n");
      out.write("\t\t\n");
      out.write("\t\t// RÃ©cupÃ¨re les suggestions\n");
      out.write("\t\tvar suggestions = $(this).attr(\"suggestions\");\n");
      out.write("\t\tsuggestionsArray = suggestions.split(\",\");\n");
      out.write("\t\t\n");
      out.write("\t\t// Formate les suggestions\n");
      out.write("\t\tsuggestions = \"\";\n");
      out.write("\t\tfor (var i=0; i<suggestionsArray.length; i++) {\n");
      out.write("\t\t\tsuggestions += \"<div class=\\\"suggestion\\\">\" + suggestionsArray[i] + \"</div>\";\n");
      out.write("\t\t}\n");
      out.write("\t\t$(\"#suggestions\").html(suggestions);\n");
      out.write("\t\tselectCorrection();\n");
      out.write("\t\t\n");
      out.write("\t\t// Affiche la popup de suggestion Ã  l'emplacement de la souris\n");
      out.write("\t\t$(\"#suggestions\").show();\n");
      out.write("\t\t$(\"#suggestions\").offset({top: e.pageY, left: e.pageX});\n");
      out.write("\t\tclic = 2;\n");
      out.write("\t\t\n");
      out.write("\t\t// Cache les suggestions quand on clic ailleurs\n");
      out.write("\t\thideSuggestions();\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function selectCorrection() {\n");
      out.write("\t$(\".suggestion\").click(function(e) {\n");
      out.write("\t\t// RÃ©cupÃ¨re la sÃ©lection\n");
      out.write("\t\tvar selection = $(this).text();\n");
      out.write("\t\t\n");
      out.write("\t\t// Remplace l'erreur par la correction\n");
      out.write("\t\tmistakeMarkup.replaceWith(selection);\n");
      out.write("\t\t\n");
      out.write("\t\t// Cache la fenÃªtre de suggestions\n");
      out.write("\t\t$(\"#suggestions\").hide();\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function hideSuggestions() {\n");
      out.write("\t$(\"body\").bind(\"click\", function(e) {\n");
      out.write("\t\tclic--;\n");
      out.write("\t\tif (clic == 0) {\n");
      out.write("\t\t\t$(\"#suggestions\").hide();\n");
      out.write("\t\t\tsuggestionsAreDisplayed = false;\n");
      out.write("\t\t\t$(\"body\").unbind(\"click\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write("function sendCorrectedText() {\n");
      out.write("alert(\"Vous devez corriger toutes les erreurs avant de valider !\");\n");
      out.write("\t$('#sendCorrectedText input[type=\"submit\"]').click(function() {\n");
      out.write("\t\tif ($('.grammerror, .orthoerror').length == 0) {\n");
      out.write("\t\t\tvar text = $('#correction').text();\n");
      out.write("\t\t\t$('#sendCorrectedText input[name=\"correctedText\"]').attr(\"value\", text);\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\talert(\"Vous devez corriger toutes les erreurs avant de valider !\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("   \n");
      out.write(" <iframe src=\"");
      out.print(request.getContextPath());
      out.write("/Correction/online_correction.jsp\" width=\"700\" height=\"600\" align=\"center\">\n");
      out.write(" </iframe>\n");
      out.write("\t\t<br/>\n");
      out.write("\t\t\n");
      out.write("<br/>\n");
      out.write("<form id=\"sendCorrectedText\" name=\"sendCorrected\" method=\"post\" action=\"/PDFCorrector/index.jsp\">\n");
      out.write("    <input type=\"hidden\" name=\"correctedText\" value=\"\"/>\n");
      out.write("    <input type=\"submit\" value=\"Valider le texte\"/>\n");
      out.write("</form>\n");
      out.write("<br/>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
