/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2011-12-15 16:40:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.servlet.browse.Files;
import com.pgrou.pdfcorrection.Main;
import java.io.File;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>PDFCorrector</title>\n");
      out.write("       \n");
      out.write("    </head>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <body>\n");
      out.write("    \n");
      out.write("\t<h1> Bienvenue sur PDFCorrector !</h1><br/>\n");
      out.write("    \t<h2> Envoi du fichier</h2>\n");
      out.write("     \t<form  id=\"frmUploadDoc\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/FileUpload?action=upload\" enctype=\"multipart/form-data\" name=\"frmUploadDoc\"> \n");
      out.write("            <table width=\"100%\" cellspacing=\"0\" class=\"tableList_1 t_space\">\n");
      out.write("                <tr>\n");
      out.write("                \n");
      out.write("                    <input name=\"uploadDocFile\" id=\"uploadDocFile\" type=\"file\" class=\"formTxtBox_1\" style=\"width:450px; background:none;\"/></br>\n");
      out.write("\t\t\t\t\t<p>Nombre de colonnes : \n");
      out.write("\t\t\t\t\t<select name=\"nbcolonnes\"> \n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1</option> \n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2</option> \n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("\t\t\t\t\t</select></p>\n");
      out.write("\t\t\t\t\t<p>Taille de l'entete haute : <input type=\"text\" name=\"entetehaute\" size=\"1\" value=\"0\"/> cm</p>\n");
      out.write("\t\t\t\t\t<p>Taille de l'entete basse : <input type=\"text\" name=\"entetebasse\" size=\"1\" value=\"0\"/> cm</p>\n");
      out.write("                    <input type=\"submit\" name=\"upload\" id=\"btnUpload\" value=\"Lancer la correction\" />\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </form>\n");
      out.write("        <br/>\n");
      out.write("          \n");
      out.write("       \n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
